-- :help <OPTION>
local opts = {
   guifont = "Hack Nerd Font Mono:h14",
   number = true,
   relativenumber = true,
   numberwidth = 2,
   expandtab = true,
   tabstop = 2,
   shiftwidth = 2,
   softtabstop = 0,
   autoindent = true,
   smartindent = true,
   ignorecase = true,
   smartcase = true,
   completeopt = { "menu", "preview" },
   cmdheight = 1,
   pumwidth = 20,
   pumheight = 10,
   backup = false,
   writebackup = false,
   swapfile = false,
   undofile = true,
   undolevels = 1000,
   undoreload = 10000,
   undodir = "/tmp/nvim_undo",
   splitbelow = true,
   splitright = true,
   showtabline = 1,
   updatetime = 250,
   timeoutlen = 500,
   hlsearch = true,
   conceallevel = 0,
   list = true,
   listchars = {
      eol = "↲",
      tab = "→ ",
      multispace = "·",
      lead = "·",
      trail = "·",
      nbsp = "␣",
   },
   wrap = true,
   showbreak = "↪ ",
   mouse = "a",
   showmode = true,
   cursorline = true,
   signcolumn = "yes",
   scrolloff = 8,
   sidescrolloff = 8,
   clipboard = "unnamedplus",
   fileencoding = "utf-8",
}

for k, v in pairs(opts) do
   vim.opt[k] = v
end
